package com.epicteam1.skimountains.feature_ski_places.core

object Constants {
    const val FIREBASE_COLLECTION_NAME = "ski_place_database"
    const val LOCAL_DATABASE_NAME = "ski_place_local_db.db"
    const val ENTITY = "entity"
    const val SKI_PLACE = "SkiPlace"
    const val CATEGORY = "Category"
    const val SAVED = "1"
    const val NOT_SAVED = "0"
    const val NO_INTERNET = "No internet connection!"
    const val SUCCESS = "Success"
    const val DETAILS = "details"
    const val SKI_PLACE_DELETED = "Ski Place Deleted"
    const val SKI_PLACE_SAVED = "Ski Place Saved"
    const val UNDO = "undo"

    const val SKIPLACE_ID = "skiPlaceId"
    const val SKIPLACE_BLACKTRAILS = "blackTrails"
    const val SKIPLACE_BLUETRAILS = "blueTrails"
    const val SKIPLACE_CABINLIFTS = "cabinLifts"
    const val SKIPLACE_CHAIRLIFTS = "chairLifts"
    const val SKIPLACE_CITIESNEARBY = "citiesNearby"
    const val SKIPLACE_GREENTRAILS = "greenTrails"
    const val SKIPLACE_HEIGHTDIFF = "heightDiff"
    const val SKIPLACE_HOWTOGETPIC = "howToGetPic"
    const val SKIPLACE_HOWTOGETTEXT = "howToGetText"
    const val SKIPLACE_LATITUDE = "latitude"
    const val SKIPLACE_LONGITUDE = "longitude"
    const val SKIPLACE_MAINPIC = "mainPic"
    const val SKIPLACE_MAXHEIGHT = "maxHeight"
    const val SKIPLACE_MAXLENGTHTRAIL = "maxLengthTrail"
    const val SKIPLACE_NAMEENG = "nameEng"
    const val SKIPLACE_NAMERUS = "nameRus"
    const val SKIPLACE_NIGHTRIDE = "nightRide"
    const val SKIPLACE_RAILWAYAVAIL = "railwayAvail"
    const val SKIPLACE_RATING = "rating"
    const val SKIPLACE_REDTRAILS = "redTrails"
    const val SKIPLACE_REGIONBIG = "regionBig"
    const val SKIPLACE_REGIONENG = "regionEng"
    const val SKIPLACE_REGIONRUS = "regionRus"
    const val SKIPLACE_SEASONDATEBEGIN = "seasonDateBegin"
    const val SKIPLACE_SEASONDATEEND = "seasonDateEnd"
    const val SKIPLACE_SUMTRAILSLENGTH = "sumTrailsLength"
    const val SKIPLACE_TOWLIFTS = "towLifts"
    const val SKIPLACE_WEBCAMERA = "webCamera"
    const val SKIPLACE_WEBCITE = "webCite"
    const val SKIPLACE_YOUTUBELINK = "youTubeLink"
    const val SKIPLACE_ENTITY = "entity"
    const val SKIPLACE_ISSAVED = "isSaved"
}